/**
 * @file BuildInfo.h
 * @brief Build information automatically updated by git hooks
 *
 * This file is automatically generated by the post-commit git hook.
 * Do not edit manually - your changes will be overwritten.
 */

#ifndef BUILDINFO_H
#define BUILDINFO_H

#define GIT_COMMIT_HASH "51ec693"
#define BUILD_TIMESTAMP "2025-11-13 11:53:51"

#endif // BUILDINFO_H
