// Autogenerated with StateSmith 0.17.5+6ec341a3c93edf598f2ca7c31f61af85857928de.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>
#include <stdint.h> // for count var


typedef enum PowerCalSm_EventId
{
    PowerCalSm_EventId_CURVE_COMPLETE = 0,
    PowerCalSm_EventId_RECORD_DATA_POINT = 1,
    PowerCalSm_EventId_RESET = 2
} PowerCalSm_EventId;

enum
{
    PowerCalSm_EventIdCount = 3
};

typedef enum PowerCalSm_StateId
{
    PowerCalSm_StateId_ROOT = 0,
    PowerCalSm_StateId_MEASUREMENTCOMPLETE = 1,
    PowerCalSm_StateId_POWERCOMPLETE = 2,
    PowerCalSm_StateId_POWERPOINT1 = 3,
    PowerCalSm_StateId_POWERPOINT2 = 4,
    PowerCalSm_StateId_POWERPOINT3 = 5,
    PowerCalSm_StateId_SSBPOINT = 6
} PowerCalSm_StateId;

enum
{
    PowerCalSm_StateIdCount = 7
};


// Generated state machine
// forward declaration
typedef struct PowerCalSm PowerCalSm;

// State machine variables. Can be used for inputs, outputs, user variables...
typedef struct PowerCalSm_Vars
{
    uint16_t count; // this var can be referenced in diagram
} PowerCalSm_Vars;


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void PowerCalSm_ctor(PowerCalSm* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void PowerCalSm_start(PowerCalSm* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void PowerCalSm_dispatch_event(PowerCalSm* sm, PowerCalSm_EventId event_id);

// Thread safe.
char const * PowerCalSm_state_id_to_string(PowerCalSm_StateId id);

// Thread safe.
char const * PowerCalSm_event_id_to_string(PowerCalSm_EventId id);

// Generated state machine
struct PowerCalSm
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    PowerCalSm_StateId state_id;
    
    // Variables. Can be used for inputs, outputs, user variables...
    PowerCalSm_Vars vars;
};

